# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False, verbose_name='BED UNIQUE ID')),
                ('bno', models.CharField(choices=[('BA', 'A'), ('BB', 'B'), ('BC', 'C'), ('BD', 'D')], max_length=2, verbose_name='bed name')),
                ('allocation_status', models.BooleanField(default=False, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('blockid', models.AutoField(primary_key=True, serialize=False, verbose_name='Block ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Hostel Block Name')),
                ('hall', models.CharField(choices=[('KG', 'KINGS'), ('QN', 'QUEENS')], max_length=2, verbose_name='hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('brefid', models.AutoField(primary_key=True, serialize=False, verbose_name='BED UNIQUE ID')),
                ('block', models.CharField(blank=True, max_length=250, verbose_name='Block of Room Allotted')),
                ('room', models.CharField(blank=True, max_length=250, verbose_name='Room Allotted')),
                ('bed', models.CharField(blank=True, max_length=15, verbose_name='Bed Allotted')),
                ('booking_status', models.BooleanField(default=False, verbose_name='status')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_of', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False, verbose_name='Room ID')),
                ('name', models.CharField(blank=True, max_length=15, verbose_name='Room Name')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='runehas.Block', verbose_name="Room's Block")),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('blockid', models.AutoField(primary_key=True, serialize=False, verbose_name='Student ID')),
                ('title', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mr'), (2, 'Miss'), (3, 'Mrs')], max_length=1, verbose_name='Title(Mr/Miss/Mrs)')),
                ('fname', models.CharField(max_length=250, verbose_name='Student First Name')),
                ('sname', models.CharField(max_length=250, verbose_name='Student Surname')),
                ('email', models.EmailField(max_length=254, verbose_name='Student Email')),
                ('mobileNo', models.PositiveIntegerField(max_length=11, verbose_name='Student Phone No')),
                ('homeAddress', models.TextField(blank=True, max_length=250, verbose_name='Permanent Home Address')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('faculty', models.CharField(max_length=250, verbose_name='Faculty')),
                ('department', models.CharField(max_length=250, verbose_name='Department')),
                ('level', models.IntegerField(max_length=3, verbose_name='Level(Year of Study)')),
                ('gender', models.CharField(choices=[('ML', 'MALE'), ('FL', 'FEMALE')], max_length=2, verbose_name='Gender')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='runehas.Room', verbose_name='Room Name'),
        ),
    ]
