# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('runehas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='blockid',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='bno',
        ),
        migrations.AddField(
            model_name='bed',
            name='bname',
            field=models.CharField(choices=[('BA', 'Bed A'), ('BB', 'Bed B'), ('BC', 'Bed C'), ('BD', 'Bed D')], max_length=2, null=True, verbose_name='bed name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Date of Booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mat_no',
            field=models.CharField(max_length=250, null=True, verbose_name="Student's Matric No"),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(verbose_name='Level(Year of Study)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobileNo',
            field=models.PositiveIntegerField(verbose_name='Student Phone No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr'), ('mi', 'Miss'), ('ms', 'Mrs')], max_length=2, verbose_name='Title(Mr/Miss/Mrs)'),
        ),
    ]
