# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runehas', '0002_auto_20170312_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
