# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runehas', '0003_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='allocation_status',
            field=models.BooleanField(default=False, help_text='not allocated by default but when value is true i.e.(checked), bed is allocated', verbose_name='Allocated Status'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bname',
            field=models.CharField(choices=[('BA', 'Bed A'), ('BB', 'Bed B'), ('BC', 'Bed C'), ('BD', 'Bed D')], max_length=2, null=True, verbose_name='Bed Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.BooleanField(default=False, verbose_name='Booking Status'),
        ),
    ]
