# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runehas', '0005_auto_20170330_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='special',
            field=models.BooleanField(default=False, help_text='Rooms are by default not special, but rooms of 400l students are specials (rooms 1,12,13 and 24 in each block)', verbose_name='400l Special Room'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bname',
            field=models.CharField(choices=[('BedA', 'Bed A'), ('BedB', 'Bed B')], max_length=2, null=True, verbose_name='Bed Name'),
        ),
        migrations.AlterField(
            model_name='block',
            name='hall',
            field=models.CharField(choices=[('KG', 'Prophet Moses Hall'), ('QN', 'Queen Esther Hall')], max_length=2, verbose_name='hostel'),
        ),
    ]
