# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170208_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='permanent home address'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='course',
            field=models.CharField(blank=True, max_length=255, verbose_name='course'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='matric_no',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='matric number'),
        ),
    ]
