# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170208_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='permanent home address'),
        ),
    ]
