# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170312_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='lga',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Local Government Area'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='State of Origin'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='department',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Level(Year of Study)'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='mat_no',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Student's Matric No"),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='mobileNo',
            field=models.PositiveIntegerField(null=True, verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
