# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170312_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='mat_no',
            field=models.CharField(blank=True, help_text="Student's matric number e.g. RUN/CMP/13/5219", max_length=250, null=True, verbose_name="Student's Matric No"),
        ),
    ]
